service: sample-nodejs

provider:
  name: aws
  runtime: nodejs10.x

# package:
#   artifact: https://s3.amazonaws.com/serverless.chinna/sample/sample-${opt:appversion}.zip

plugins:
  - serverless-plugin-datadog

functions:
  hello:
    handler: handler.hello
    environment:
      DD_API_KEY: ${env:DD_API_KEY}
      DD_FLUSH_TO_LOG: 'true'
      DD_TRACE_ENABLED: 'true'
    events:
      - http:
          path: hello
          method: get
    reservedConcurrency: ${opt:reservedConcurrency, 5}
