service: sample-nodejs

provider:
  name: aws
  runtime: nodejs10.x

package:
  artifact: https://s3.amazonaws.com/serverless.chinna/sample/sample-${opt:appversion}.zip

plugins:
  - serverless-plugin-datadog

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: post
    reservedConcurrency: ${opt:reservedConcurrency, 5}
