name: Serverless Deployement

on:
  push:
    branches:
      - master

env: 
  APP_VERSION: 'dev'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Copy files to the test website with the AWS CLI
        run: aws s3 ls
          
      - name: npm install and zip
        run: npm install && zip -r bodenstein-dev.zip .

      - name: Uplaod to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude '*' --include 'bodenstein-dev.zip'
        env:
          AWS_S3_BUCKET: 'serverless.chinna'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          DEST_DIR: 'bodenstein'

      - name: Serverless
        uses: serverless/github-action@v1.53.0
        with:
          args: >-
            deploy
            --stage ${env.APP_VERSION}
            --reservedConcurrency 2
            --appversion dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
