name: Serverless Deployement

on:
  push:
    branches:
      - master

env: 
  APP_VERSION: 'dev'
  NODE_VERSION: "10.16.0"
  SERVERLESS_VERSION: "1.79.0"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Access
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "DD_API_KEY=${{ secrets.DATA_DOG_API_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV

      # - name: Configure AWS credentials from Test account
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      - name: Package
        run: |
          npm install -g serverless@{{ env.SERVERLESS_VERSION }} && \
          npm run clean && \
          npm install && \
          zip -r sample-dev.zip .
      
      - name: Publish to S3
        run: aws s3 cp ./sample-dev.zip s3://serverless.chinna/sample/sample-dev.zip

      - name: Serverless Deploy
        run: |
          npm install && \
          serverless deploy \
            --reservedConcurrency 2
            --appversion dev
            --force