name: Serverless Deployement

on:
  push:
    branches:
      - master

env: 
  APP_VERSION: 'dev'
  NODE_VERSION: "10.16.0"
  SERVERLESS_VERSION: "1.79.0"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
        DD_API_KEY: ${{ secrets.DD_API_KEY }}


    steps:
      - uses: actions/checkout@v1

      - name: npm install dependencies
        run: npm install
        
      - name: Serverless
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy
          