name: Serverless Deployement

on:
  push:
    branches:
      - master

env: 
  APP_VERSION: 'dev'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: serverless/github-action@v1.53.0

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package
        run: |
          npm install -g serverless@$1.79.0 && \
          npm run clean && \
          npm install && \
          zip -r sample-dev.zip .
      
      - name: Publish to S3
        run: aws s3 cp ./sample-dev.zip s3://serverless.chinna/sample/sample-dev.zip

      - name: Serverless Deploy
        run: |
          npm install && \
          serverless deploy \
            --reservedConcurrency 2
            --appversion dev
            --force